config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  devise_for :users
  root 'homes#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'welcome/index'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  has_paper_trail
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :user_id, presence: true
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id'
end

app/models/complain.rb
class Complain < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  validates :follower_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/poly_comment.rb
class PolyComment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true
  validates :image, presence: true
  has_many :poly_comments, as: :commentable, dependent: :destroy
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :likes, dependent: :destroy
  has_many :complains, dependent: :destroy
  def liked?(user)
    likes.find { |like| like.user_id == user.id }
  end
end

app/models/story.rb
# frozen_string_literal: true

class Story < ApplicationRecord
  belongs_to :user
  has_one_attached :story, dependent: :destroy
  validates :user_id, presence: true
  validates :story, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: {
    admin: 'admin',
    user: 'user'
  }
  validates :user_name, uniqueness: true
  validates :user_name, presence: true
  has_many :poly_comments, as: :commentable, dependent: :destroy
  has_one_attached :avatar, dependent: :destroy
  has_many :stories, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :follows, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize_user
  before_action :set_post, only: %i[show edit update destroy]
  before_action :show_data, only: [:show]
  def index
    @comments = Comment.all
  end

  def show; end

  def new
    @post = if params[:parent_id].nil?
              Post.find(params[:post_id])
            else
              Post.find(Comment.find(params[:parent_id]).post_id)
            end
    @comment = @post.comments.new(parent_id: params[:parent_id])
  end

  def edit; end

  def create
    post_id = params[:post_id]
    byebug
    user_id = Post.find(params[:post_id]).user_id
    @user = User.find(user_id)
    if params[:comment][:parent_id] == ''
      @comment = User.find(user_id).posts.find(post_id).comments.create(comment: params[:comment][:comment],
                                                                        user_id: current_user.id, post_id: params[:post_id])
    else
      @comment = User.find(user_id).posts.find(post_id).comments.find(params[:comment][:parent_id]).replies.create(
        user_id: user_id, post_id: params[:post_id], comment: params[:comment][:comment]
      )
    end
    respond_to do |format|
      if @comment.save
        format.html { redirect_to '', notice: 'Comment was successfully created.' } # changed the redirect to @post
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def set_post
    @comment = Comment.find(params[:id])
  end

  def authorize_user
    return if user_signed_in?

    redirect_to(new_user_session_path)
  end
end

app/controllers/follows_controller.rb
# frozen_string_literal: true

class FollowsController < ApplicationController
  def create
    @follow = Follow.new(follower_id: current_user.id, user_id: params[:id])
    return unless @follow.save

    FollowMailer.with(follow: @follow).new_follow_email.deliver_later
    redirect_to root_path, notice: 'Followed successfully.'
  end

  def destroy
    @user = User.find(params[:id])
    return unless @user.follows.find_by(follower_id: current_user.id).destroy

    redirect_to root_path, notice: 'Unfollowed successfully.'
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize_user
  def new
    @post = Post.new
  end

  def like
    @post = Post.find(params[:id])
    Like.create(user_id: current_user.id, post_id: @post.id)
    redirect_to root_path
  end

  def complain
    @post = Post.find(params[:id])
    Complain.create(user_id: current_user.id, post_id: @post.id)
    redirect_to root_path
  end

  def destroy_like
    return unless Like.destroy(params[:id])

    redirect_to root_path
  end

  def create
    @post = Post.new(post_params)

    # @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    Post.destroy(@post.id)
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:description, :image, :user_id)
  end

  def authorize_user
    return if user_signed_in?

    redirect_to(new_user_session_path)
  end
end

app/controllers/stories_controller.rb
# frozen_string_literal: true

class StoriesController < ApplicationController
  def index; end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    return unless @story.save

    redirect_to root_path, notice: 'Story was successfully created.'
  end

  def show
    @story = Story.find(params[:id])
  end

  def destroy; end

  def story_params
    params.require(:story).permit(:story, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy] # probably want to keep using this

  # GET /users
  # GET /users.json
  def index
    @user = User.all
  end

  # # GET /users/1
  # # GET /users/1.json
  def show
    @user = if params[:search].nil?
              User.find_by(user_name: params[:id])
            else
              User.find_by(user_name: params[:search])
            end
  end

  # GET /users/1/edit
  def edit; end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).pemit(:role, :user_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/poly_comments_helper.rb
module PolyCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% unless comment.parent_id || !comment.persisted? %>
<div class="card">
  <div class="card-body">
    <%= comment.comment %>
   <%= link_to 'reply', new_post_comment_path(@posts, parent_id: comment.id), remote: true, class: 'd-block' %>
      </div>
  </div>
  <% if comment.replies.any? %>
    <% comment.replies.each do |reply| %> 
      <%= render partial: 'comments/reply', locals: { reply: reply } %>
    <% end %>
  <% end %>
  <% end %>
  <div id="reply-form-<%= comment.id %>"></div>
  

app/views/comments/_reply.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= reply.comment %>
  </div>
</div>

app/views/comments/_reply_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_with(model: [@post, @comment]) do |f| %>
      <%= f.hidden_field :parent_id %>
      <div class="form-group">
        <%= f.label 'Reply' %>
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', post_path(@post), class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_with(model: [@post, @comment]) do |f| %>
      <%= f.hidden_field :parent_id %>
      <div class="form-group">
        <%= f.label 'Reply' %>
        <%= f.text_area :comment, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', post_path(@post), class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/comments/new.js.erb
document.querySelector("#reply-form-<%= @comment.parent_id %>").innerHTML = ("<%= j render 'reply_form', comment: @comment %>")

app/views/comments/show.html.erb
<%= render @post.comments %>

app/views/posts/_form.html.erb
<%= form_for @post do |form| %>
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>
  <div>
    <%= form.hidden_field :user_id %>
    <%= form.hidden_field :user_id, value:current_user.id %>
  </div>
  <%= form.submit "Save Post", class: 'btn btn-primary' %>
<% end %>

app/views/posts/edit.html.erb
<div class="card my-5">
  <div class="card-body">
    <h1>Edit Post</h1>

    <%= render 'form'%>

    <div class="mt-2">
      <%= link_to 'Destroy',Post.find(params[:id]), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mr-2' %> # moved the destroy button from index to here (optional)
      <%= link_to 'Back', posts_path, class: 'btn btn-light' %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%# <%= render "form", post: @post %>
<div class="card my-5">
  <div class="card-body">
    <h1>New Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Back', posts_path, class: 'btn btn-light mt-2' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="card my-1"> # place this card blow the post body.
  <div class="card-body">
    <p class="font-weight-bold">Comments</p>
    <%  post=Post.find(params[:id])%>
    <%= form_with(model: [post, post.comments.build]) do |f| %>
      <div class="form-group">
        <%= f.label 'New comment' %>
        <%= f.text_area :comment, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.hidden_field :post_id,value: params[:id] %>
        <%= f.hidden_field :user_id,value: current_user.id %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>
<%= render post.comments%>

app/views/stories/_form.html.erb
<h1>for story</h1>
<%= form_with(model: story) do |form| %>
  <div>
    <%= form.hidden_field :user_id, value: current_user.id%>
  </div>
  <div>
    <%= form.file_field :story %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/index.html.erb
 <p class="card-text"><%=image_tag @story.story, :size => "1085x600"%></p>

app/views/stories/new.html.erb
<%=render 'form', story: @story%>

app/views/stories/show.html.erb
<p class="card-text"><%=image_tag @story.story, :size => "1085x600"%></p>

app/views/users/_admin.html.erb
<h3>Users Are</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Users</th>
      <th scope="col">Account</th>
      <th scope="col">Profile</th>
    </tr>
  </thead>
<% User.find_each(start: 2)do |user|%>
  <tbody>
    <tr>
    <td><%=user.user_name%></td>	
      <td><%= button_to "Delete User Account", destroy_user_path(user), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete,class:"btn btn-danger"%></td>
    <td><a class="btn btn-info" href="/users/<%="#{user.user_name}"%>">Show Profile</a></td>	
    </tr>
  </tbody>
<% end %>
</table>
<h3>Complains Are</h3>
<%Complain.all.each do |complain|%>
  <%post=Post.find(complain.post_id)%>
  <p class="card-text"><%=image_tag post.image.to_s, :size => "1085x600"%></p>
  <%= link_to "Destroy", post_path(post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } , class: 'btn btn-danger mr-2'%><br><br >
  <%= button_to "Delete User Account", destroy_user_path(User.find(post.user_id)), data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" }, method: :delete,class:"btn btn-danger"%>
  <% end %>

app/views/users/_form.html.erb
<%= search_form_for @q do |f| %>
<%= f.label :name %>
<%= f.text_field :name_cont, class: 'form-control' %>
<%= f.submit class: 'btn btn-primary' %>
<% end %>
<%= link_to "Clear", request.path, class: "btn btn-default" %>

app/views/users/_style.html.erb
<style>
:root {
  font-size: 10px;
}

*,
*::before,
*::after {
    box-sizing: border-box;
}

body {
  font-family: "Open Sans", Arial, sans-serif;
    min-height: 100vh;
    background-color: #fafafa;
    color: #262626;
    padding-bottom: 3rem;
}

img {
  display: block;
}

.container {
  max-width: 93.5rem;
    margin: 0 auto;
    padding: 0 2rem;
}

.btn {
  display: inline-block;
    font: inherit;
    background: none;
    border: none;
    color: inherit;
    padding: 0;
    cursor: pointer;
}

.btn:focus {
  outline: 0.5rem auto #4d90fe;
}

.visually-hidden {
    position: absolute !important;
    height: 1px;
    width: 1px;
    overflow: hidden;
    clip: rect(1px, 1px, 1px, 1px);
}

/* Profile Section */

.profile {
  padding: 5rem 0;
}

.profile::after {
  content: "";
    display: block;
    clear: both;
}

.profile-image {
  float: left;
    width: calc(33.333% - 1rem);
    display: flex;
    justify-content: center;
    align-items: center;
    margin-right: 3rem;
}

.profile-image img {
  border-radius: 50%;
}

.profile-user-settings,
.profile-stats,
.profile-bio {
  float: left;
    width: calc(66.666% - 2rem);
}

.profile-user-settings {
  margin-top: 1.1rem;
}

.profile-user-name {
  display: inline-block;
    font-size: 3.2rem;
    font-weight: 300;
}

.profile-edit-btn {
  font-size: 1.4rem;
    line-height: 1.8;
    border: 0.1rem solid #dbdbdb;
    border-radius: 0.3rem;
    padding: 0 2.4rem;
    margin-left: 2rem;
}

.profile-settings-btn {
  font-size: 2rem;
    margin-left: 1rem;
}

.profile-stats {
  margin-top: 2.3rem;
}

.profile-stats li {
  display: inline-block;
    font-size: 1.6rem;
    line-height: 1.5;
    margin-right: 4rem;
    cursor: pointer;
}

.profile-stats li:last-of-type {
  margin-right: 0;
}

.profile-bio {
  font-size: 1.6rem;
    font-weight: 400;
    line-height: 1.5;
    margin-top: 2.3rem;
}

.profile-real-name,
.profile-stat-count,
.profile-edit-btn {
  font-weight: 600;
}

/* Gallery Section */

.gallery {
    display: flex;
    flex-wrap: wrap;
    margin: -1rem -1rem;
    padding-bottom: 3rem;
}

.gallery-item {
  position: relative;
    flex: 1 0 22rem;
    margin: 1rem;
    color: #fff;
    cursor: pointer;
}

.gallery-item:hover .gallery-item-info,
.gallery-item:focus .gallery-item-info {
  display: flex;
    justify-content: center;
    align-items: center;
    position: absolute;
    top: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.3);
}

.gallery-item-info {
  display: none;
}

.gallery-item-info li {
  display: inline-block;
    font-size: 1.7rem;
    font-weight: 600;
}

.gallery-item-likes {
  margin-right: 2.2rem;
}

.gallery-item-type {
  position: absolute;
    top: 1rem;
    right: 1rem;
    font-size: 2.5rem;
    text-shadow: 0.2rem 0.2rem 0.2rem rgba(0, 0, 0, 0.1);
}

.fa-clone,
.fa-comment {
  transform: rotateY(180deg);
}

.gallery-image {
  width: 100%;
    height: 100%;
    object-fit: cover;
}

/* Loader */

.loader {
  width: 5rem;
    height: 5rem;
    border: 0.6rem solid #999;
    border-bottom-color: transparent;
    border-radius: 50%;
    margin: 0 auto;
    animation: loader 500ms linear infinite;
}

/* Media Query */

@media screen and (max-width: 40rem) {
  .profile {
    display: flex;
        flex-wrap: wrap;
        padding: 4rem 0;
    }

    .profile::after {
      display: none;
    }

    .profile-image,
    .profile-user-settings,
    .profile-bio,
    .profile-stats {
      float: none;
        width: auto;
    }

    .profile-image img {
      width: 7.7rem;
    }

    .profile-user-settings {
      flex-basis: calc(100% - 10.7rem);
        display: flex;
        flex-wrap: wrap;
        margin-top: 1rem;
    }

    .profile-user-name {
      font-size: 2.2rem;
    }

    .profile-edit-btn {
        order: 1;
        padding: 0;
        text-align: center;
        margin-top: 1rem;
    }

    .profile-edit-btn {
      margin-left: 0;
    }

    .profile-bio {
      font-size: 1.4rem;
        margin-top: 1.5rem;
    }

    .profile-edit-btn,
    .profile-bio,
    .profile-stats {
      flex-basis: 100%;
    }

    .profile-stats {
      order: 1;
        margin-top: 1.5rem;
    }

    .profile-stats ul {
      display: flex;
        text-align: center;
        padding: 1.2rem 0;
        border-top: 0.1rem solid #dadada;
        border-bottom: 0.1rem solid #dadada;
    }

    .profile-stats li {
      font-size: 1.4rem;
        flex: 1;
        margin: 0;
    }

    .profile-stat-count {
      display: block;
    }
}

/* Spinner Animation */

@keyframes loader {
  to {
    transform: rotate(360deg);
    }
}

/*

The following code will only run if your browser supports CSS grid.

Remove or comment-out the code block below to see how the browser will fall-back to flexbox & floated styling. 

*/

@supports (display: grid) {
  .profile {
    display: grid;
        grid-template-columns: 1fr 2fr;
        grid-template-rows: repeat(3, auto);
        grid-column-gap: 3rem;
        align-items: center;
    }

    .profile-image {
      grid-row: 1 / -1;
    }

    .gallery {
      display: grid;
        grid-template-columns: repeat(auto-fit, minmax(22rem, 1fr));
        grid-gap: 2rem;
    }

    .profile-image,
    .profile-user-settings,
    .profile-stats,
    .profile-bio,
    .gallery-item,
    .gallery {
      width: auto;
        margin: 0;
    }

    @media (max-width: 40rem) {
      .profile {
        grid-template-columns: auto 1fr;
            grid-row-gap: 1.5rem;
        }

        .profile-image {
          grid-row: 1 / 2;
        }

        .profile-user-settings {
          display: grid;
            grid-template-columns: auto 1fr;
            grid-gap: 1rem;
        }

        .profile-edit-btn,
        .profile-stats,
        .profile-bio {
          grid-column: 1 / -1;
        }

        .profile-user-settings,
        .profile-edit-btn,
        .profile-settings-btn,
        .profile-bio,
        .profile-stats {
          margin: 0;
        }
    }
}

</style>

app/views/users/_user.html.erb
<header>
	<div class="container">

		<div class="profile">

			<div class="profile-image">
        <% if user.avatar.attached?%>
         <%= image_tag user.avatar,alt: "avatar", height: "152", width: "152"%>
        <% else%>
				  <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="">
        <% end %>
			</div>

			<div class="profile-user-settings">
            
			<h1 class="profile-user-name"><%= user.user_name%></h1>    
						<% if user.follows.where(follower_id: current_user.id).exists?%>
            <%= button_to 'Unfollow', "/follows/#{user.id}",method: :delete,class: "btn btn-secondary"%>
            <% else %>
						<% if user!=current_user%>
            <%= button_to 'Follow', follows_path(id:@user), method: :post,class: "btn btn-primary"%>
						<% end %>
            <% end %>
		  </div>
			<div class="profile-stats">

				<ul>
					<li><span class="profile-stat-count"><%=user.posts.count%></span> posts</li>
					<li><span class="profile-stat-count"><%=user.follows.count%></span> followers</li>
					<li><span class="profile-stat-count"><%=Follow.where(follower_id: user.id).count
%></span> following</li>
				</ul>

			</div>
<br>
<br>
<br>
<br>

			<div class="profile-bio">

				<p><span class="profile-real-name"><%=user.user_name%></span><%= user.bio%></p>

			</div>
<br>
<br>
<br>

		</div>
		<!-- End of profile section -->

	</div>
	<!-- End of container -->

</header>

<main>
<% if user==current_user||current_user.admin?
%>  
	<div class="container">
    <%user.posts.each do|post|%>
		<div class="gallery">
			<div class="gallery-item" tabindex="0">
				 <%=image_tag post.image.to_s,class: "gallery-image"%>
                 <%= link_to "Destroy", post_path(post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } , class: 'btn btn-danger mr-2'%>
         <div class="gallery-item-type">
					<span class="visually-hidden">Gallery</span><i class="fas fa-clone" aria-hidden="true"></i>
				</div>
        <div class="gallery-item-info">
					<ul>
						<li class="gallery-item-likes"><span class="visually-hidden">Likes:</span><i class="fas fa-heart" aria-hidden="true"></i> <%= post.likes.count%></li>
						<li class="gallery-item-comments"><span class="visually-hidden">Comments:</span><i class="fas fa-comment" aria-hidden="true"></i><%= post.poly_comments.count %></li>
					</ul>
          </div>
			</div>
		</div>
    <% end %>
    
		<!-- End of gallery -->

		<div class="loader"></div>
<% elsif user.follows.where(follower_id: current_user.id).exists? %>
  
	<div class="container">
    <%user.posts.each do|post|%>
		<div class="gallery">
			<div class="gallery-item" tabindex="0">
				 <%=image_tag post.image.to_s,class: "gallery-image"%>
         <div class="gallery-item-type">
					<span class="visually-hidden">Gallery</span><i class="fas fa-clone" aria-hidden="true"></i>
				</div>
        <div class="gallery-item-info">
					<ul>
						<li class="gallery-item-likes"><span class="visually-hidden">Likes:</span><i class="fas fa-heart" aria-hidden="true"></i><%= post.likes.count%> </li>
						<li class="gallery-item-comments"><span class="visually-hidden">Comments:</span><i class="fas fa-comment" aria-hidden="true"></i><%= post.poly_comments.count %></li>
					</ul>
        </div>
			</div>
		</div>
    <% end %>
    
		<!-- End of gallery -->

		<div class="loader"></div>
            <% end %>
	</div>
	<!-- End of container -->

</main>
<%= render 'style'%>

app/views/users/history.html.erb
<if current_user.admin?>
<table class="table">
<thead>
<tr>
<th scope="col">Item_Type</th>
<th scope="col">Event</th>
<th scope="col">User</th>
</tr>
</thead>
<% @history.each do |history| %>
    <tbody>
    <tr>
    <td><%= history.item_type %></td>
    <td><%= history.event %></td>
    <% if history.whodunnit %>
    <td><%= User.find(history.whodunnit).user_name %></td>
    <% else %>
    <td>nil</td>
    <% end %>
    </tr>
    </tbody>
    <% end %>
</table>
<end>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if @user==nil%>
    <p>No user Found</p>
<% elsif @user.admin?%>
  <% if !current_user.admin? %>
    <p>No user Found</p>
  <% else%>
    <%=render 'admin'%>
  <% end %>
<% else%>
 <%=render 'user',user: @user%>
<% end %>